name: Build & Test
on: [push]
jobs:
  utest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: x64
      - name: Build external
        run: make build_ext
      - name: Setup environment
        run: make setup_venv
      - name: Build C++ Code
        run: make build_libnumstore
      - name: Build Cython Code
        run: make build_cython
      - name: Run python tests
        run: make test

